* first upload to Debian archive, thanks to the hard work of Leonardo   Rodrigues de Mello, Matthias Albert, Li Daobing and Neil Wilson,   closes: #419924 * extend init script with status function, remove boilerplate   do_reload function and fix whitespace typo * remove mount patch which is included in upstream sources * include copyright text in debian/copyright, include author list,   include more specific homepage * switch from Ubuntu universe back to standard Debian sections * New Upstream Version * public release (closes LP#246715) * new upstream release 1.3.9.

diff --git a/debian/glusterfs-server.init b/debian/glusterfs-server.init
--- a/debian/glusterfs-server.init
+++ b/debian/glusterfs-server.init
@@ -5,23 +5,27 @@
 # Required-Stop:     $local_fs $network
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: glusterfs server
-# Description:       Starts and stops the glusterfs server.
+# Short-Description: GlusterFS server
+# Description:       GlusterFS is a cluster filesystem. This service
+#                    provides the GlusterFS server functionality which
+#                    is configured via a volume spec file usually
+#                    located in the /etc/glusterfs directory.
 #                    
 ### END INIT INFO
 
 # Author: Chris AtLee <chris@atlee.ca>
-# Patched by: Matthias Albert < matthias@linux4experts.de>
+# Patched by: Matthias Albert <matthias@linux4experts.de>
 # Upgraded by: Neil Wilson <neil@brightbox.co.uk>
+# Slightly extended by: Christian Meder <chris@absolutegiganten.org>
 
 PATH=/usr/sbin:/usr/bin:/sbin:/bin
-DESC="GlusterFS Server"
+DESC="GlusterFS server"
 NAME=glusterfsd
 DAEMON=/usr/sbin/$NAME
 CONFIGFILE=/etc/glusterfs/glusterfs-server.vol
-DAEMON_ARGS="-f $CONFIGFILE"
 PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
+DAEMON_ARGS="-p $PIDFILE -f $CONFIGFILE"
+SCRIPTNAME=/etc/init.d/glusterfs-server
 
 # Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
@@ -80,16 +84,23 @@ do_stop()
 }
 
 #
-# Function that sends a SIGHUP to the daemon/service
+# Function that provides status information about the service
 #
-do_reload() {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
-	return 0
+do_status()
+{
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null
+	RETVAL="$?"
+	if [ "$RETVAL" = 1 ]; then
+            log_success_msg "$DESC is running."
+            exit 0
+        fi
+        if [ "$RETVAL" = 0 ]; then
+            log_failure_msg "$DESC is not running."
+            exit 1
+        else
+            log_failure_msg "Couldn't determine status of $DESC."
+            exit 3
+        fi
 }
 
 case "$1" in
@@ -140,9 +151,12 @@ case "$1" in
 		;;
 	esac
 	;;
+  status)
+        do_status
+        ;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload|status}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
 	exit 3
 	;;
 esac
